version: "3.9"

services:
  api:
    build: .
    container_name: telco_api
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: always

  dashboard:
    build: .
    container_name: telco_streamlit
    command: streamlit run app_streamlit.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: always
